Implementation of RegCB Algorithm
VowpalWabbit/coba pull request #7
Opened 2021-07-08 18:32 UTC by anrath

2021-07-09 03:06 UTC, mrucker requested changes
Hey, overall this looks really good. I just left a few nitpicky comments. I'll start turning up the heat a little bit the more we code together. Please don't get frustrated or feel attacked. This is me simply recognizing you are growing as a developer and can handle more picky feedback. Also, code reviews are always largely opinion so don't read too much into it if you disagree.

Once you address my comments or tell me you disagree and don't want to make the recommend changes for whatever reason I'll accept the code.

2021-07-09 03:06 UTC, mrucker commented on coba/learners/regCB.py
> +    """A learner using the RegCB algorithm from "Practical Contextual Bandits with Regression Oracles" by Foster et al.
Do you mind adding a little more explanation explaining the relationship between the two citations? That is the algorithm is due to Foster while the online bin search implementation is due to Bietti?

2021-07-11 02:00 UTC, anrath commented on coba/learners/regCB.py
> +            for term in self._terms:
How would you instantiate context_names so that this works with product when context is None?

2021-07-11 14:35 UTC, mrucker commented on coba/learners/regCB.py
> +            for term in self._terms:
Looks like something like `context_names = ['']`. You can do little experiments in python on the command line to get a sense.

![image](https://user-images.githubusercontent.com/966578/125199319-47bd6e00-e22b-11eb-850c-f23f9d174036.png)

2021-07-11 14:45 UTC, mrucker commented on coba/learners/regCB.py
> +            for term in self._terms:
In fact, I played around a little more with `product` just now in the CLI and you could go straight to:

    temp_array = [ "".join(names) for names in product(*[context_names]*term[0], *[action_names]*term[1]) ]

The only thing with all this we just need to double check and make sure features still align with their names. I imagine you tested that with the old logic so you probably have a better sense of how things should line up than me.

2021-07-12 14:00 UTC, mrucker approved these changes

2021-07-12 14:01 UTC, merged